# Copyright (c) 2020 Rafal Bedzkowski
# Released under the term specified in file LICENSE

name: 'run-cppcheck'
description: 'Perform static code analysis using Cppcheck'
author: 'Rafal Bedzkowski https://github.com/Bedzior'
inputs:
  path:
    description: 'Path to your project'
    required: true
  generateReport:
    description: 'Whether to generate an XML report'
    required: false
    default: true
  enabledChecks:
    description: 'Which checks are enabled'
    required: false
    default: 'all'
  enableInconclusive:
    description: 'Enable inconclusive checks'
    required: false
    default: false
  excludes:
    description: 'Which directories or files to exclude from analysis; format: paths prefixed with `-I`, space-delimited'
    required: false
    default: ''
  includes:
    description: 'Include paths; format: directories prefixed with `-i`, space-delimited'
    required: false
    default: ''
  reportName:
    description: 'Name of your report'
    required: false
    default: ${{ github.repository }}
outputs:
  reportPath:
    description: 'Path to XML report file'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check'
  color: 'gray-dark'
