# Copyright (c) 2020 Rafal Bedzkowski
# Released under the term specified in file LICENSE

name: 'run-cppcheck'
description: 'Perform static code analysis using Cppcheck'
author: 'Rafal Bedzkowski https://github.com/Bedzior'
inputs:
  debug:
    description: 'Debug script run to troubleshoot configuration errors'
    required: false
    default: false
  enabled checks:
    description: 'Which checks are enabled'
    required: false
    default: 'all'
  enable inconclusive:
    description: 'Enable inconclusive checks'
    required: false
    default: false
  excludes:
    description: 'Which directories or files to exclude from analysis; format: paths prefixed with `-I`, space-delimited'
    required: false
    default: ''
  generate report:
    description: 'Whether to generate an XML report'
    required: false
    default: true
  includes:
    description: 'Include paths; format: directories prefixed with `-i`, space-delimited'
    required: false
    default: ''
  path:
    description: 'Path to your project'
    required: true
    default: '.'
  report name:
    description: 'Name of your report'
    required: false
    default: ${{ github.repository }}
  verbose:
    description: 'Verbose Cppcheck error descriptions'
    required: false
    default: false

outputs:
  reportPath:
    description: 'Path to XML report file'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check'
  color: 'gray-dark'
