# Copyright (c) 2020 Rafal Bedzkowski
# Released under the term specified in file LICENSE

name: 'run-cppcheck'
description: 'Perform static code analysis using Cppcheck'
author: 'Rafal Bedzkowski https://github.com/Bedzior'
inputs:
  debug:
    description: 'Debug script run to troubleshoot configuration errors'
    required: false
    default: false
  enabled checks:
    description: 'Which checks are enabled'
    required: false
    default: 'all'
  enable inconclusive:
    description: 'Enable inconclusive checks'
    required: false
    default: false
  exclude from check:
    description: 'Which directories to exclude from analysis; format: paths prefixed with `-i`, space-delimited'
    required: false
    default: ''
  generate report:
    description: 'Whether to generate an XML report'
    required: false
    default: true
  include directories:
    description: 'Include paths; format: directories prefixed with `-I`, space-delimited'
    required: false
    default: ''
  path:
    description: 'Path to your project; either this or "project" ought to be set'
    required: false
    default: ${{ github.workspace }}
  project:
    description: 'Project file containing compile lists and commands (Cppcheck GUI, CMake, Visual Studio, C++ Builder are currently supported); either this or "path" ought to be set'
    required: false
  report name:
    description: 'Name of your report'
    required: false
    default: ${{ github.repository }}
  root:
    description: 'Root directory of the project (current directory by default)'
    required: false
    default: ${{ github.workspace }}
  verbose:
    description: 'Verbose Cppcheck error descriptions'
    required: false
    default: false

outputs:
  reportPath:
    description: 'Path to XML report file'
  htmlReportPath:
    description: 'Path to HTML report directory'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check'
  color: 'gray-dark'
