name: Tests

on: [push, pull_request]

jobs:
  input-tests:
    name: Utilities tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        depth: 1
    - name: Build test Docker image
      id: build-docker
      run: |
        IMAGE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'):test
        docker build . --file Dockerfile --tag $IMAGE
        echo "::set-env name=DOCKER_IMAGE::${IMAGE}"
    - name: Run all input tests
      run: |
        for f in input-tests/*.sh ; do
          docker run -t $DOCKER_IMAGE --entrypoint "/bin/sh" -c input-tests/${f}
        done
        docker container prune
  action-tests:
    name: Testing GitHub Action in action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: No project or path test
      uses: ./
    - name: Test shouldn't succeed
      if: success()
      run: exit 1
